OCPBUGS-17359: test/e2e: Don't use openshift/origin-node
openshift/cluster-ingress-operator pull request #970
Opened 2023-08-04 00:23 UTC by Miciah

Use the "openshift/tools" image from the cluster image registry instead of using the "openshift/origin-node" image pullspec in E2E tests.

Before this change, the E2E tests were inadvertently pulling the "openshift/origin-node" image from Docker Hub and getting rate-limited.

The choice to use "openshift/tools" is based on a similar change here: https://github.com/openshift/origin/pull/24887/commits/4cbb844d1d5f3a3ac6dd08325db17b807e7129f2

Follow-up to #410 and #451.

* `test/e2e/util_test.go` (`buildEchoPod`, `buildSlowHTTPDPod`): Replace the "openshift/origin-node" image pullspec with "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest".

2023-08-04 16:28 UTC, candita commented
/retest-required

2023-08-04 19:44 UTC, candita commented
> hsts_policy_test.go:147: failed to find header [max-age=0;preload;includesubdomains]: timed out waiting for the condition

/test e2e-azure-operator

2023-08-04 23:55 UTC, Miciah commented
Using a Cluster Bot cluster to run `TestHstsPolicyWorks`, I see that the kubelet is failing to pull "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest" for the "hsts-policy-echo" pod:
```text
Events:
  Type     Reason          Age                From               Message
  ----     ------          ----               ----               -------
  Normal   Scheduled       48s                default-scheduler  Successfully assigned hsts-policy-namespace/hsts-policy-echo to ip-10-0-26-86.ec2.internal
  Normal   AddedInterface  48s                multus             Add eth0 [10.129.2.3/23] from ovn-kubernetes
  Normal   BackOff         19s (x3 over 47s)  kubelet            Back-off pulling image "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest"
  Warning  Failed          19s (x3 over 47s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling         5s (x3 over 48s)   kubelet            Pulling image "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest"
  Warning  Failed          5s (x3 over 48s)   kubelet            Failed to pull image "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest": rpc error: code = Unknown desc = reading manifest
latest in image-registry.openshift-image-registry.svc:5000/openshift/tools: authentication required
  Warning  Failed          5s (x3 over 48s)   kubelet            Error: ErrImagePull
```

2023-08-05 00:12 UTC, Miciah commented
Hm, sometimes the test is able to pull the image, and sometimes it gets that auth error, during repeated tests on the same cluster.

2023-08-05 00:34 UTC, Miciah commented
Watching `oc -n openshift-image-registry logs -ldocker-registry=default --tail=0`, the image registry is sometimes denying the image pull during one test run:
```text
time="2023-08-05T00:26:31.931724609Z" level=error msg="OpenShift access denied: no opinion" go.version="go1.20.5 X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=403cb81a-1e08-42bf-b3c3-c65f57d2b619 http.request.method=GET http.request.remoteaddr="100.64.0.7:39038" http.request.uri=/v2/openshift/tools/manifests/latest http.request.useragent="cri-o/1.27.1-4.rhaos4.14.gitab7845e.el9 go/go1.20.5 os/linux arch/amd64" openshift.auth.user=anonymous vars.name=openshift/tools vars.reference=latest
time="2023-08-05T00:26:31.93178121Z" level=warning msg="error authorizing context: access denied" go.version="go1.20.5 X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=403cb81a-1e08-42bf-b3c3-c65f57d2b619 http.request.method=GET http.request.remoteaddr="100.64.0.7:39038" http.request.uri=/v2/openshift/tools/manifests/latest http.request.useragent="cri-o/1.27.1-4.rhaos4.14.gitab7845e.el9 go/go1.20.5 os/linux arch/amd64" vars.name=openshift/tools vars.reference=latest
time="2023-08-05T00:26:31.931848511Z" level=info msg=response go.version="go1.20.5 X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=20c2a054-f06d-4f62-8a0c-b4e5185a6284 http.request.method=GET http.request.remoteaddr="100.64.0.7:39038" http.request.uri=/v2/openshift/tools/manifests/latest http.request.useragent="cri-o/1.27.1-4.rhaos4.14.gitab7845e.el9 go/go1.20.5 os/linux arch/amd64" http.response.contenttype=application/json http.response.duration=2.437939ms http.response.status=401 http.response.written=158
time="2023-08-05T00:26:48.31509818Z" level=error msg="OpenShift access denied: no opinion" go.version="go1.20.5 X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=c775a56a-3125-4211-9a5a-a8493e2ac309 http.request.method=GET http.request.remoteaddr="100.64.0.7:48090" http.request.uri=/v2/openshift/tools/manifests/latest http.request.useragent="cri-o/1.27.1-4.rhaos4.14.gitab7845e.el9 go/go1.20.5 os/linux arch/amd64" openshift.auth.user=anonymous vars.name=openshift/tools vars.reference=latest
time="2023-08-05T00:26:48.315145541Z" level=warning msg="error authorizing context: access denied" go.version="go1.20.5 X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=c775a56a-3125-4211-9a5a-a8493e2ac309 http.request.method=GET http.request.remoteaddr="100.64.0.7:48090" http.request.uri=/v2/openshift/tools/manifests/latest http.request.useragent="cri-o/1.27.1-4.rhaos4.14.gitab7845e.el9 go/go1.20.5 os/linux arch/amd64" vars.name=openshift/tools vars.reference=latest
time="2023-08-05T00:26:48.315177572Z" level=info msg=response go.version="go1.20.5 X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=1d4f1da9-9f01-40ea-9b21-571b7d5d691d http.request.method=GET http.request.remoteaddr="100.64.0.7:48090" http.request.uri=/v2/openshift/tools/manifests/latest http.request.useragent="cri-o/1.27.1-4.rhaos4.14.gitab7845e.el9 go/go1.20.5 os/linux arch/amd64" http.response.contenttype=application/json http.response.duration=2.396133ms http.response.status=401 http.response.written=158
```
And then the image registry is allowing the pull in the next run:
```text
time="2023-08-05T00:27:05.807299045Z" level=info msg="authorized request" go.version="go1.20.5 X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=a2a449f4-ce12-4f30-80a9-b9f050782826 http.request.method=GET http.request.remoteaddr="100.64.0.7:58848" http.request.uri=/v2/openshift/tools/manifests/latest http.request.useragent="cri-o/1.27.1-4.rhaos4.14.gitab7845e.el9 go/go1.20.5 os/linux arch/amd64" openshift.auth.user="system:serviceaccount:hsts-policy-namespace:default" vars.name=openshift/tools vars.reference=latest
time="2023-08-05T00:27:05.926022483Z" level=info msg="response completed" go.version="go1.20.5 X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=a2a449f4-ce12-4f30-80a9-b9f050782826 http.request.method=GET http.request.remoteaddr="100.64.0.7:58848" http.request.uri=/v2/openshift/tools/manifests/latest http.request.useragent="cri-o/1.27.1-4.rhaos4.14.gitab7845e.el9 go/go1.20.5 os/linux arch/amd64" http.response.contenttype=application/vnd.docker.distribution.manifest.v2+json http.response.duration=123.8248ms http.response.status=200 http.response.written=1252 openshift.auth.user="system:serviceaccount:hsts-policy-namespace:default" vars.name=openshift/tools vars.reference=latest
time="2023-08-05T00:27:05.926060873Z" level=info msg=response go.version="go1.20.5 X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=8bfe698c-5476-48bc-b740-0c763cce1b30 http.request.method=GET http.request.remoteaddr="100.64.0.7:58848" http.request.uri=/v2/openshift/tools/manifests/latest http.request.useragent="cri-o/1.27.1-4.rhaos4.14.gitab7845e.el9 go/go1.20.5 os/linux arch/amd64" http.response.contenttype=application/vnd.docker.distribution.manifest.v2+json http.response.duration=123.883201ms http.response.status=200 http.response.written=1252
```

2023-08-05 00:37 UTC, Miciah commented
The successful request has `openshift.auth.user="system:serviceaccount:hsts-policy-namespace:default"`, and the failing request has `openshift.auth.user=anonymous`.  :thinking:...

2023-08-05 01:54 UTC, Miciah commented
The two new commits seem to prevent the "authentication required" errors.  In manual testing with these changes, I have seen the test pass over 20 times and fail 0 times.

2023-08-05 19:55 UTC, Miciah commented
[e2e-aws-ovn-serial failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-ovn-serial/1687641888498126848) because `Undiagnosed panic detected in pod` failed:
```text
{  pods/openshift-cloud-network-config-controller_cloud-network-config-controller-c5f776f49-j76xk_controller_previous.log.gz:E0805 03:33:08.727528       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)}
```
I believe this a known issue: [OCPBUGS-17151](https://issues.redhat.com/browse/OCPBUGS-17151).  

Also, `[sig-storage] PersistentVolumes-local Stress with local volumes [Serial] should be able to process many pods and reuse local volumes` failed:
```text
{  fail [test/e2e/storage/persistent_volumes-local.go:522]: persistentvolumes "local-pvkbdlx" not found
Error: exit with code 1
Ginkgo exit error 1: exit with code 1}
```
This is also a known issue: [OCPBUGS-14930](https://issues.redhat.com/browse/OCPBUGS-14930).
/test e2e-aws-ovn-serial

[e2e-aws-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator/1687641888443600896) because must-gather failed.
/test e2e-aws-operator

2023-08-09 15:15 UTC, Miciah commented
[e2e-aws-ovn-serial failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-ovn-serial/1687915179926360064) with same failure for test `[sig-storage] PersistentVolumes-local Stress with local volumes [Serial] should be able to process many pods and reuse local volumes`:
```text
{  fail [test/e2e/storage/persistent_volumes-local.go:522]: persistentvolumes "local-pvd2fz8" not found
Error: exit with code 1
Ginkgo exit error 1: exit with code 1}
```

2023-08-09 15:15 UTC, Miciah commented
https://github.com/openshift/cluster-ingress-operator/compare/839d1b2ea9450bc7d15d3aa3008fd6fe9e0ccaed..4216df06b6a9731693f8d227123992e1e59b6a59 rebases for #970.

2023-08-10 03:19 UTC, Miciah commented
[e2e-aws-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator/1689294644128518144) because must-gather failed.
/test e2e-aws-operator

[e2e-gcp-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-gcp-operator/1689294644359204864) because `TestAllowedSourceRanges`, `TestAllowedSourceRangesStatus`, `TestInternalLoadBalancer`, and `TestUserDefinedIngressController` failed.  It appears that these tests failed because it took too long for the LB that each tests creates to get created or updated.  For example, the `TestInternalLoadBalancer` test creates an IngressController named "testinternalloadbalancer" that requests an LB, and the test then runs a polling loop with a 5-minute timeout waiting for the LB to be provisioned, but the LB is actually taking more than 5 minutes to become ready, counting from the time the pod is scheduled to the time the LB is reported ready:
```text
% jq < events.json -c '.items|sort_by(.metadata.creationTimestamp)|.[]|select(.involvedObject.namespace=="openshift-ingress" and (.reason=="Scheduled" or .reason=="EnsuredLoadBalancer"))|[.metadata.creationTimestamp,.involvedObject.kind,.involvedObject.name,.reason]' | grep -w -e testinternalloadbalancer    
["2023-08-09T16:14:03Z","Pod","router-testinternalloadbalancer-84f74cb78b-qx9xq","Scheduled"]
["2023-08-09T16:19:29Z","Service","router-testinternalloadbalancer","EnsuredLoadBalancer"]
```
Similarly, `TestUserDefinedIngressController` creates an IngressController named "testuserdefinedingresscontroller" and waits 5 minutes for it to be ready, and it is taking more than 5 minutes to become ready:
```text
% jq < events.json -c '.items|sort_by(.metadata.creationTimestamp)|.[]|select(.involvedObject.namespace=="openshift-ingress" and (.reason=="Scheduled" or .reason=="EnsuredLoadBalancer"))|[.metadata.creationTimestamp,.involvedObject.kind,.involvedObject.name,.reason]' | grep -w -e testuserdefinedingresscontroller
["2023-08-09T16:16:50Z","Pod","router-testuserdefinedingresscontroller-78bb97f5b6-675cl","Scheduled"]
["2023-08-09T16:22:13Z","Service","router-testuserdefinedingresscontroller","EnsuredLoadBalancer"]
```
The `TestAllowedSourceRangesStatus` test likewise creates an IngressController named "sourcerangesstatus", waits 5 minutes, then modifies configuration related to the LB and waits for the update:
```text
% jq < events.json -c '.items|sort_by(.metadata.creationTimestamp)|.[]|select(.involvedObject.namespace=="openshift-ingress" and (.reason=="Scheduled" or .reason=="EnsuredLoadBalancer"))|[.metadata.creationTimestamp,.involvedObject.kind,.involvedObject.name,.reason]' | grep -w -e sourcerangesstatus
["2023-08-09T16:11:00Z","Pod","router-sourcerangesstatus-9cd78d588-dqbsv","Scheduled"]
["2023-08-09T16:16:11Z","Service","router-sourcerangesstatus","EnsuredLoadBalancer"]
["2023-08-09T16:32:03Z","Pod","router-sourcerangesstatus-9cd78d588-z88pw","Scheduled"]
["2023-08-09T16:32:53Z","Service","router-sourcerangesstatus","EnsuredLoadBalancer"]
```
`TestAllowedSourceRanges` in contrast creates a deliberately misconfigured IngressController named "sourcerange", so the IngressController doesn't get provisioned at first; then the test modifies the IngressController with valid configuration so that the LB can be provisioned.  Then, the test waits 1 minute for the LB to be provisioned, but the LB takes over a minute to become ready:
```text
% jq < events.json -c '.items|sort_by(.metadata.creationTimestamp)|.[]|select(.involvedObject.namespace=="openshift-ingress" and (.reason=="Scheduled" or .reason=="EnsuredLoadBalancer"))|[.metadata.creationTimestamp,.involvedObject.kind,.involvedObject.name,.reason]' | grep -w -e sourcerange
["2023-08-09T16:11:01Z","Pod","router-sourcerange-7b886595c8-prkt6","Scheduled"]
["2023-08-09T16:32:04Z","Pod","router-sourcerange-7b886595c8-cqhhz","Scheduled"]
["2023-08-09T16:33:44Z","Service","router-sourcerange","EnsuredLoadBalancer"]
```
We might need to adjust these timeouts, but if ELBs are consistently taking longer to provision than they used to, we also should look into that.  Looking into [the kube-controller logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-gcp-operator/1689294644359204864/artifacts/e2e-gcp-operator/gather-extra/artifacts/pods/openshift-kube-controller-manager_kube-controller-manager-ci-op-3z6hgvr4-76b3b-vlf49-master-2_kube-controller-manager.log), there is a rather conspicuous 3m39s gap from 16:14 to 16:17, between `Error syncing endpoint slices for service "openshift-ingress/router-testinternalloadbalancer", retrying. Error: EndpointSlice informer cache is out of date` and `Ensuring load balancer for service openshift-ingress/router-testinternalloadbalancer`, and then a somewhat conspicuous 1m43s gap from 16:17 to 16:29 before `Ensured load balancer`:
```text
% grep -h -e router-testinternalloadbalancer -- namespaces/openshift-kube-controller-manager/pods/kube-controller-manager-*/kube-controller-manager/kube-controller-manager/logs/*.log 
2023-08-09T16:14:03.482683918Z I0809 16:14:03.482609       1 replica_set.go:571] "Too few replicas" replicaSet="openshift-ingress/router-testinternalloadbalancer-84f74cb78b" need=1 creating=1
2023-08-09T16:14:03.483178036Z I0809 16:14:03.483086       1 event.go:307] "Event occurred" object="openshift-ingress/router-testinternalloadbalancer" fieldPath="" kind="Deployment" apiVersion="apps/v1" type="Normal" reason="ScalingReplicaSet" message="Scaled up replica set router-testinternalloadbalancer-84f74cb78b to 1"
2023-08-09T16:14:03.502208701Z I0809 16:14:03.502132       1 event.go:307] "Event occurred" object="openshift-ingress/router-testinternalloadbalancer-84f74cb78b" fieldPath="" kind="ReplicaSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulCreate" message="Created pod: router-testinternalloadbalancer-84f74cb78b-qx9xq"
2023-08-09T16:14:03.512974851Z I0809 16:14:03.512911       1 deployment_controller.go:503] "Error syncing deployment" deployment="openshift-ingress/router-testinternalloadbalancer" err="Operation cannot be fulfilled on deployments.apps \"router-testinternalloadbalancer\": the object has been modified; please apply your changes to the latest version and try again"
2023-08-09T16:14:07.057662221Z I0809 16:14:07.057585       1 replica_set.go:461] ReplicaSet "router-testinternalloadbalancer-84f74cb78b" will be enqueued after 30s for availability check
2023-08-09T16:14:07.082018038Z W0809 16:14:07.081951       1 endpointslice_controller.go:297] Error syncing endpoint slices for service "openshift-ingress/router-testinternalloadbalancer", retrying. Error: EndpointSlice informer cache is out of date
2023-08-09T16:17:46.872430243Z I0809 16:17:46.871676       1 controller.go:388] Ensuring load balancer for service openshift-ingress/router-testinternalloadbalancer
2023-08-09T16:17:46.872430243Z I0809 16:17:46.871722       1 controller.go:887] Adding finalizer to service openshift-ingress/router-testinternalloadbalancer
2023-08-09T16:17:46.872511683Z I0809 16:17:46.872423       1 event.go:307] "Event occurred" object="openshift-ingress/router-testinternalloadbalancer" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
2023-08-09T16:19:03.442314693Z I0809 16:19:03.442087       1 deployment_controller.go:597] "Deployment has been deleted" deployment="openshift-ingress/router-testinternalloadbalancer"
2023-08-09T16:19:03.442314693Z I0809 16:19:03.442161       1 garbagecollector.go:533] "Processing item" item="[monitoring.coreos.com/v1/ServiceMonitor, namespace: openshift-ingress, name: router-testinternalloadbalancer, uid: 56f [...]

2023-08-10 07:04 UTC, frobware requested changes

2023-08-10 23:12 UTC, Miciah commented
[e2e-gcp-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-gcp-operator/1689682873700847616) because `TestUserDefinedIngressController` and `TestUnmanagedDNSToManagedDNSInternalIngressController` failed.  From the test output, this looks like the issue described in https://github.com/openshift/cluster-ingress-operator/pull/970#issuecomment-1672492378.  (To do: File a bug report for this issue.)
/test e2e-gcp-operator

[e2e-hypershift failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-hypershift/1689682873730207744) because `TestNodePool/NodePool_Tests_Group/TestNodepoolMachineconfigGetsRolledout/EnsureNoCrashingPods` and `TestNodePool/NodePool_Tests_Group/TestNTOMachineConfigGetsRolledOut/EnsureNoCrashingPods` failed.
/test e2e-hypershift

[e2e-aws-ovn-single-node failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-ovn-single-node/1689652991788847104) because 338 of 3821 tests failed.  The first failure in the list was an `Undiagnosed panic detected in pod` failure:
```text
{  pods/openshift-controller-manager_controller-manager-7f55874d69-twwz8_controller-manager.log.gz:E0810 16:47:11.628946       1 runtime.go:79] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x38e6da0), concrete:(*runtime._type)(0x3aa81e0), asserted:(*runtime._type)(0x3d79a20), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.BuildConfig)
pods/openshift-controller-manager_controller-manager-7f55874d69-twwz8_controller-manager.log.gz:E0810 16:47:12.630035       1 runtime.go:79] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x38e6da0), concrete:(*runtime._type)(0x3aa81e0), asserted:(*runtime._type)(0x3d79a20), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.BuildConfig)}
```
I filed [OCPBUGS-17632](https://issues.redhat.com/browse/OCPBUGS-17632) for this panic.  Let's see what happens if we retry the job.  
/test e2e-aws-ovn-single-node

[e2e-gcp-ovn failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-gcp-ovn/1689652991973396480) because `[sig-network] pods should successfully create sandboxes by adding pod to network` failed.  Let's see if that happens again.  
/test e2e-gcp-ovn

2023-08-11 03:05 UTC, Miciah commented
[e2e-gcp-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-gcp-operator/1689776734045474816) because `TestUnmanagedDNSToManagedDNSInternalIngressController` failed again.  I see this test failing for #872 too.  
/test e2e-gcp-operator

2023-08-11 19:07 UTC, Miciah commented
[e2e-gcp-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-gcp-operator/1689835529492762624) because `TestInternalLoadBalancer` failed because it timed out while waiting for the LB to be provisioned.

2023-08-11 22:43 UTC, Miciah commented
I filed [OCPBUGS-17670](https://issues.redhat.com/browse/OCPBUGS-17670) for the issue that LBs can take over 5 minutes to provision on GCP.

2023-08-11 23:56 UTC, Miciah commented
[e2e-azure-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/970/pull-ci-openshift-cluster-ingress-operator-master-e2e-azure-operator/1690101593501863936) because `TestManagedDNSToUnmanagedDNSIngressController` failed.  I filed [OCPBUGS-17671](https://issues.redhat.com/browse/OCPBUGS-17671) for this issue.  
/test e2e-azure-operator

2023-08-12 01:49 UTC, merged

2023-10-25 16:27 UTC, Miciah commented
/cherry-pick release-4.13